### ISSUE TITLE
iOS 13 not working

### ISSUE THREAD

**Issue by guoxianzhe** [whitedogg13/react-native-nfc-manager#216]
environment:
    "react-native-nfc-manager": "^2.0.1",
    "react-native": "0.61.1",

android is perfect! 
**BUT**
when i want to read card tag on the **iOS13**,the screen always stay at this step:
![image](https://user-images.githubusercontent.com/53285945/67851099-05cec000-fb4d-11e9-9c5f-538833d1711c.png)

xcode shows:
![image](https://user-images.githubusercontent.com/53285945/67851194-3f073000-fb4d-11e9-9821-5de658520709.png)

is that something wrong what i had?

**Comment by whitedogg13** [comment]
@guoxianzhe Sorry for the late response. The UI is perfectly normal, it's just the default prompt shown by iOS, and it will dismiss once the tag is scanned.

**Comment by guoxianzhe** [comment]
@whitedogg13 sorry,when the ic card is in contact with the iphone, the iphone has no reaction. 
the screen always stay at this step.

**Comment by acasademont** [comment]
@whitedogg13 we're seeing the same, if we send the comand first we see the iOS prompt but nothing in return.

**Comment by whitedogg13** [comment]
Hi all, here’re some updates. We have found that some tags cannot be correctly scanned by iOS 13, as discussed in #210 . Can you guys report what tags you’re using?

**Comment by guoxianzhe** [comment]
i used 'example/AppV2.js' to get the tag
![image](https://user-images.githubusercontent.com/53285945/68394001-69da2f80-01b0-11ea-8be4-f866a085294f.png)

saw the iOS prompt but nothing in return.

**Comment by acasademont** [comment]
@whitedogg13 sure, it's the NXP NTAG213

**Comment by acasademont** [comment]
A normal NDEF scanning app like the ones you could do before iOS13 (GoToTags for example) works well with the tags and reads the NDEF record without problems.

**Comment by whitedogg13** [comment]
Could you share a minimal project for me to debug？since I cannot reproduce this one, it’s hard to guess what’s going wrong.

**Comment by acasademont** [comment]
@whitedogg13 ok we found it, seems like we enabled the capabilities on our Identifiers page on the apple developers website but we didn't actually add the NFC capability to our Xcode project...I believe @guoxianzhe might be facing the same issue. For reference, the .entitlements file should have these lines:

<img width="909" alt="Screenshot 2019-11-07 at 17 48 20" src="https://user-images.githubusercontent.com/825021/68409107-d0e2ee80-0186-11ea-86ef-0c0ba2071aca.png">

**Comment by acasademont** [comment]
Sorry and thanks for your time!!

**Comment by acasademont** [comment]
The problem is that we added the entitlements as the guide https://github.com/hansemannn/iOS-NFC-Example suggest, but there's a new entitlement that needs to be added. The correct entitlements file is 

```xml
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
  <string>NDEF</string>
  <string>TAG</string>
</array>
```

the "TAG" one is the new one in iOS 13 that the guide doesn't mention. We didn't see until we added the entitlements via Xcode GUI

**Comment by whitedogg13** [comment]
@acasademont Awesome! Sorry for not keeping the doc up to date, would you mind sending a PR to update readme? I will be very happy to accept that!

**Comment by acasademont** [comment]
Sure, we'll try ;)

**Comment by acasademont** [comment]
Done in #217 @guoxianzhe could you confirm if this also fixes your issue?

**Comment by guoxianzhe** [comment]
@acasademont @whitedogg13 

I changed my entitlements files like this:
![image](https://user-images.githubusercontent.com/53285945/68741743-c666a000-0631-11ea-8438-36686739bb73.png)

It seems still not working :( 

I tried to use example directory in my project, it's still not working on iOS13

about iOS setting:
i just finish these steps:
![image](https://user-images.githubusercontent.com/53285945/68741911-3543f900-0632-11ea-9c81-291cb8430802.png) info.plist

![image](https://user-images.githubusercontent.com/53285945/68741743-c666a000-0631-11ea-8438-36686739bb73.png) .entitlements

![image](https://user-images.githubusercontent.com/53285945/68741971-5f95b680-0632-11ea-9f98-429332472c0d.png) 


it seems all right of my setting

**Comment by inkCrazy** [comment]
我也有相同的问题，我使用的版本是"react-native-nfc-manager": "^1.2.2",
桥接文件中使用的是NFCNDEFReaderSession类，don't have the class of 'NFCTagReaderSession'.  
NFCTagReaderSession allows to scan native tags like ISO14443, ISO15693, ISO18092
NFCNDEFReaderSession supports discovery of NDEF tag objects and read/write operations for those
NFCNDEFReaderSession无法识别没有支持的芯片，我使用的芯片类别是ISO 14443-3A NXP Mifare Ultralight-NTAG213

this is iOS13 demo: is good for NFCTagReaderSession
```
#import "ViewController.h"
#import <CoreNFC/CoreNFC.h>
#import <MessageUI/MessageUI.h>

@interface ViewController ()<NFCTagReaderSessionDelegate>

@property (weak, nonatomic) IBOutlet UILabel *readText;
@property(strong,nonatomic)NFCTagReaderSession *session;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
}

- (IBAction)scanNFC:(UIButton *)sender {
    self.session = [[NFCTagReaderSession alloc] initWithPollingOption:(NFCPollingISO14443 | NFCPollingISO15693 | NFCPollingISO15693) delegate:self queue:nil];
    self.session.alertMessage = @"读取卡片，请将卡片靠近手机";
    [self.session beginSession]; //开始识别 弹出识别提示框
}

- (void)tagReaderSession:(NFCTagReaderSession *)session didInvalidateWithError:(NSError *)error API_AVAILABLE(ios(13.0)) API_UNAVAILABLE(watchos, macos, tvos) {
    NSLog(@"didInvalidateWithError => %@", error.localizedRecoverySuggestion);
}

- (void)tagReaderSessionDidBecomeActive:(NFCTagReaderSession *)session API_AVAILABLE(ios(13.0)) API_UNAVAILABLE(watchos, macos, tvos) {
    NSLog(@"tagReaderSessionDidBecomeActive => %@", session);
}

-(void)tagReaderSession:(NFCTagReaderSession *)session didDetectTags:(NSArray<__kindof id<NFCTag>> *)tags{
    NSLog(@"didDetectTags => %@", tags);
}
```

**Comment by whitedogg13** [comment]
@inkCrazy Please use v2.0.1 instead, v1 contains no iOS 13 support.

**Comment by whitedogg13** [comment]
@guoxianzhe Your setting looks good to me. Can you confirm your tag can be scanned by other iOS NFC app like NXP tag info? Just to make sure it's not related to the tag.

**Comment by guoxianzhe** [comment]
@whitedogg13 
Yes,the tag that I used is perfectly by other iOS NFC app.

**Comment by mencomao** [comment]
On ios13, I scan a blank Ntag213 first, and then scan a Ntag213 with data. At this time, there is no response. If I scan the Ntag213 with data directly, the data can be read.

**Comment by mencomao** [comment]
@whitedogg13 On ios13, I scan a blank Ntag213 first, and then scan a Ntag213 with data. At this time, there is no response. If I scan the Ntag213 with data directly, the data can be read.

**Comment by vadermemo** [comment]
Same issue here

"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-nfc-manager": "^2.0.1"
  },

Dont work on iOS 13 and iphone 11.

Even when I active the shorcuts on Iphone and make the configuration to Automatization> Personal>NFC my cards are readables correctly.

Any can resolve this bug!?

Best regards.

**Comment by vadermemo** [comment]
Same issue here

"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-nfc-manager": "^2.0.1"
  },

Dont work on iOS 13 and iphone 11.

Even when I active the shorcuts on Iphone and make the configuration to Automatization> Personal>NFC my cards are readables correctly.

Any can resolve this bug!?

Best regards.

**Comment by vadermemo** [comment]
> Hi all, here’re some updates. We have found that some tags cannot be correctly scanned by iOS 13, as discussed in #210 . Can you guys report what tags you’re using?

Same issue with clone cards Arduino.

**Comment by vadermemo** [comment]
> > Hi all, here’re some updates. We have found that some tags cannot be correctly scanned by iOS 13, as discussed in #210 . Can you guys report what tags you’re using?
> 
> Same issue with clone cards Arduino.

Even doesn´t work with NFC TAG Keychain 13.56MHz for Arduino (Blue)

**Comment by dmorais92** [comment]
Followed the Mifare example and cannot scan Mifare Classic or Plus and it doesn't seem to be working on iOS 13, iPhone X

**Comment by Megatron4537** [comment]
Heads up for those struggling with NTAG213, my NTAG213 supports MifareUltralight, NfcA and Ndef, on iOS, using the pair [setEventListener,registerTagEvent] I can detect the tags but not read its UID, to do so i had to use the mifare example and use [requestTechnology(NfcTech.MifareIOS), getTag] (this gives the tag UID)

**Comment by whitedogg13** [comment]
Hi @Megatron4537 thanks for sharing! 

What you mentioned is indeed the correct solution. BTW, the limitation around `uid` is because iOS won’t give us the `uid` when requesting `Ndef` technology, and it’s is a platform limitation we cannot bypass.

Thanks!

**Comment by whitedogg13** [comment]
Hi all, some update for people facing the issue `only see the iOS prompt but nothing can be scanned`:

Please try to use [this example](https://github.com/whitedogg13/nfc-test-app) to see if it works.
(in issue #250, some developer reports the issue been fixed by trying above example, although the root cause is not identified)

**Comment by vanronaldo2** [comment]
Hello.
I have the same issue, it fixed by following it.
https://github.com/whitedogg13/react-native-nfc-manager/issues/289#issue-616577045

**Comment by bingbing720** [comment]
I have the same issue, it fixed by following the below.
https://github.com/whitedogg13/react-native-nfc-manager/issues/289

**Comment by guoxianzhe** [comment]
I fixed it by use other card
